const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const statusSource = fs.readFileSync('Domain/StatusEffects.cs', 'utf8');
const traitSource = fs.readFileSync('Domain/Traits.cs', 'utf8');
const engineSource = fs.readFileSync('Domain/GameEngine.cs', 'utf8');
const previewSource = fs.readFileSync('Api/AttackPreviewService.cs', 'utf8');
const appSource = fs.readFileSync('wwwroot/app.js', 'utf8');
const assetManifest = JSON.parse(fs.readFileSync('wwwroot/config/ui-assets.json', 'utf8'));

function classBody(source, className) {
  const start = source.indexOf(`class ${className}`);
  assert.notEqual(start, -1, `${className} class not found`);
  const next = source.indexOf('\npublic sealed class ', start + 1);
  return source.slice(start, next === -1 ? source.length : next);
}

test('common statuses and aura dispel rules are wired correctly', () => {
  const beastRageStatus = classBody(statusSource, 'BeastRageStatus');
  const magicPowerStatus = classBody(statusSource, 'MagicPowerStatus');
  const deployingStatus = classBody(statusSource, 'DeployingStatus');
  const harvestStatus = classBody(statusSource, 'HarvestStatus');
  const pendingHarvestStatus = classBody(statusSource, 'PendingHarvestStatus');
  const guardOathStatus = classBody(statusSource, 'GuardOathStatus');
  const strongAttackStatus = classBody(statusSource, 'StrongAttackStatus');
  const magicSurgeStatus = classBody(statusSource, 'MagicSurgeStatus');

  assert.match(statusSource, /class ExhaustionStatus[\s\S]*?DamageType\.Physical[\s\S]*?packet\.Amount = Math\.Max\(1, packet\.Amount \/ 2\)/);
  assert.match(statusSource, /class ErosionStatus[\s\S]*?DamageType\.Magical[\s\S]*?packet\.Amount = Math\.Max\(1, packet\.Amount \/ 2\)/);
  assert.match(statusSource, /abstract class TurnDurationStatus[\s\S]*?DefaultTurns = 2/);
  assert.match(statusSource, /RemainingTurns--/);
  assert.match(strongAttackStatus, /TurnDurationStatus\("strong-attack", true, sourceCharacterId, turns\)/);
  assert.match(magicSurgeStatus, /TurnDurationStatus\("magic-surge", true, sourceCharacterId, turns\)/);
  assert.match(magicSurgeStatus, /DamageType\.Magical/);
  assert.match(magicSurgeStatus, /Math\.Ceiling\(packet\.Amount \* 1\.5\)/);
  assert.doesNotMatch(statusSource, /class WeaknessStatus/);
  assert.doesNotMatch(statusSource, /class PendingWeaknessStatus/);
  assert.match(statusSource, /virtual bool IsAttackBuff => false/);
  assert.match(statusSource, /virtual bool IsDispellable => true/);
  assert.doesNotMatch(statusSource, /IsAttackEnhancement/);
  assert.doesNotMatch(statusSource, /IsAttackBuffDispelTarget/);
  assert.match(beastRageStatus, /IsAttackBuff => true/);
  assert.match(beastRageStatus, /IsDispellable => false/);
  assert.match(magicPowerStatus, /StatusEffect\("magic-power", false, sourceCharacterId\)/);
  assert.doesNotMatch(magicPowerStatus, /IsAttackBuff => true/);
  assert.match(magicPowerStatus, /IsDispellable => false/);
  assert.match(deployingStatus, /readyOnTurnNumber/);
  assert.match(deployingStatus, /ReadyOnTurnNumber/);
  assert.match(deployingStatus, /ExpireIfReady\(int turnNumber\)/);
  assert.match(engineSource, /new DeployingStatus\(character\.Id, character\.PlayerId, GetDeployingReadyTurnNumber\(state\)\)/);
  assert.match(engineSource, /private static int GetDeployingReadyTurnNumber\(GameState state\) =>\s*CurrentRoundNumber\(state\) \* 2 \+ 3/);
  assert.match(engineSource, /ExpireReadyDeployingStatuses\(state\)/);
  assert.match(engineSource, /state\.Players\.SelectMany\(player => player\.Characters\)/);
  assert.match(engineSource, /ThreadCutMoraleDamagePerMark = 2/);
  assert.match(engineSource, /var count = CountThreadCutMarks\(target\)/);
  assert.match(engineSource, /DealMoraleDamage\(state, target, ThreadCutMoraleDamagePerMark \* count/);
  assert.doesNotMatch(engineSource, /Math\.Clamp\(CountThreadCutMarks/);
  assert.match(engineSource, /\("attackMoraleDamage", L10n\.Raw\(attackPacket\.MoraleDamage\)\)/);
  assert.match(engineSource, /\("counterMoraleDamage", L10n\.Raw\(counterPacket\.MoraleDamage\)\)/);
  assert.match(appSource, /playLayeredDamageFloats\(defender, \{ moraleAmount: attackMoraleDamage, hpAmount: attackDamage/);
  assert.match(appSource, /if \(hp > 0\)\s+window\.setTimeout\(\(\) => damageFloat\(target, hp, type, \{ label: 'HP' \}\), 210\)/);
  assert.match(appSource, /if \(value > 0\) animateHpOrbLoss\(target, value\);/);
  assert.match(appSource, /function animateHpOrbLoss\(card, amount\)/);
  assert.match(appSource, /updatePendingVisualHp\(card, nextHp\)/);
  assert.match(appSource, /await animateBpRecoveryToHp\(bpRecoveryAmount, payload\.data\);/);
  assert.match(appSource, /function updatePendingVisualMorale\(card, morale\)/);
  assert.match(appSource, /animateMoraleRingRecovery\(card, value, \{ finalMorale: finalCharacter\?\.morale \}\)/);
  assert.match(appSource, /updatePendingVisualMorale\(card, nextMorale\)/);
  assert.doesNotMatch(appSource, /force: true, label: 'HP'/);
  assert.equal(appSource.includes("attackMoraleDamage > 0 || attackDamage <= 0 ? null : `-${attackDamage}`"), true);
  assert.equal(appSource.includes("moraleAmount > 0 || totalAmount <= 0 ? null : `-${totalAmount}`"), true);
  assert.match(harvestStatus, /IsAttackBuff => true/);
  assert.doesNotMatch(harvestStatus, /IsDispellable => false/);
  assert.doesNotMatch(pendingHarvestStatus, /IsDispellable => false/);
  assert.doesNotMatch(pendingHarvestStatus, /IsAttackBuff => true/);
  assert.match(traitSource, /status\.IsBuff[\s\S]*?status\.IsDispellable/);
  assert.match(traitSource, /context\.Next\(attackBuffs\.Count\)/);
  assert.match(traitSource, /Statuses\.Remove\(attackBuff\)/);
  assert.match(traitSource, /GameEngine\.AddExhaustion\(exchange\.Defender, owner\.Id\)/);
  assert.match(traitSource, /GameEngine\.AddErosion\(exchange\.Defender, owner\.Id\)/);
  assert.match(engineSource, /internal static bool AddTrembling[\s\S]*?RefreshTurns\(turns\)/);
  assert.match(traitSource, /status\.Id == "magic-power"/);
  assert.match(guardOathStatus, /StatusEffect\("guard-oath", true, sourceCharacterId\)/);
  assert.match(guardOathStatus, /public int Stacks/);
  assert.match(guardOathStatus, /packet\.Source != DamageSource\.ActiveAttack/);
  assert.doesNotMatch(guardOathStatus, /IsDispellable => false/);
  assert.match(previewSource, /ForecastOutgoingDamage/);
  assert.match(previewSource, /"chant" when canConsumeChargeStatuses && type == DamageType\.Magical => damage \* 2/);
  assert.match(previewSource, /"magic-surge" when damageSource == DamageSource\.ActiveAttack && type == DamageType\.Magical/);
  assert.match(previewSource, /"guard-oath" when source == DamageSource\.ActiveAttack && type == DamageType\.Physical/);
  assert.doesNotMatch(previewSource, /weaknessEnragedMonster/);
  assert.equal(assetManifest.bindings.statuses['magic-power'], 'status.magic-power');
  assert.equal(assetManifest.bindings.statuses['magic-surge'], 'status.magic-surge');
  assert.equal(assetManifest.bindings.statuses['mighty-strike'], 'status.mighty-strike');
  assert.equal(assetManifest.bindings.statuses.exhaustion, 'status.exhaustion');
  assert.equal(assetManifest.bindings.statuses.erosion, 'status.erosion');
  assert.equal(assetManifest.bindings.statuses['guard-oath'], 'status.guard-oath');
});
