const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const engineSource = fs.readFileSync('Domain/GameEngine.cs', 'utf8');
const gameStateSource = fs.readFileSync('Domain/GameState.cs', 'utf8');
const dtoSource = fs.readFileSync('Api/GameDtos.cs', 'utf8');
const appSource = fs.readFileSync('wwwroot/app.js', 'utf8');

test('shield costs depend on whether a shared shield still exists', () => {
  assert.match(engineSource, /MaxActionPoints\s*=\s*5/);
  assert.match(engineSource, /FirstShieldCost\s*=\s*2/);
  assert.match(engineSource, /ReinforcedShieldCost\s*=\s*1/);
  assert.match(engineSource, /ReinforcedShieldBonus\s*=\s*2/);
  assert.match(engineSource, /DefenseCommandReinforcedShieldCap\s*=\s*5/);
  assert.match(engineSource, /MaxDefenseCommandReinforceSourceShield\s*=\s*3/);
  assert.doesNotMatch(engineSource, /MaxSharedShieldValue/);
  assert.match(engineSource, /CanReinforceShield\(PlayerState player\)/);
  assert.match(engineSource, /public static bool CanReinforceShield\(PlayerState player\) =>\s*player\.SharedShield > 0 && player\.SharedShield <= MaxDefenseCommandReinforceSourceShield;/);
  assert.match(engineSource, /player\.SharedShield = Math\.Min\(DefenseCommandReinforcedShieldCap, player\.SharedShield \+ ReinforcedShieldBonus\)/);
  assert.match(engineSource, /isReinforcing && !CanReinforceShield\(player\)/);
  assert.match(engineSource, /highestPhysicalDefense[\s\S]*?highestMagicalDefense[\s\S]*?IncreaseSharedShield\(state, player, shield, triggerResponses: false\)/);
  assert.doesNotMatch(gameStateSource, /SharedShieldReinforcedThisTurn/);
  assert.doesNotMatch(engineSource, /SharedShieldReinforcedThisTurn/);
  assert.match(engineSource, /ClearShieldLayerIfBroken\(PlayerState player\)/);
  assert.match(engineSource, /targetOwner\.SharedShield -= absorbed;\s*ClearShieldLayerIfBroken\(targetOwner\);/);
  assert.match(engineSource, /ClearShieldLayerIfBroken\(owner\);/);
  assert.match(engineSource, /state\.ActionPoints\s*-=\s*shieldCost/);
  assert.match(engineSource, /public static bool CanDeployShield\(GameState state\)/);
  assert.match(engineSource, /player\.SharedShield <= 0 \|\| CanReinforceShield\(player\)/);
  assert.match(dtoSource, /int NextShieldCost/);
  assert.match(dtoSource, /GameEngine\.CanDeployShield\(state\)/);
  assert.match(dtoSource, /GameEngine\.GetShieldCost\(state\.ActivePlayer\)/);
  assert.match(appSource, /game\.nextShieldCost/);
  assert.match(appSource, /shieldActionIsReinforce\s*=\s*game\.nextShieldCost === 1 && activeSharedShield > 0/);
  assert.match(appSource, /shieldActionIsOpen\s*=\s*game\.nextShieldCost === 2 && activeSharedShield <= 0/);
  assert.match(appSource, /canReinforceShield\s*=\s*game\.canDeployShield && shieldActionIsReinforce/);
  assert.match(appSource, /if \(shieldActionIsOpen\)/);
  assert.match(appSource, /else if \(shieldActionIsReinforce\)/);
  assert.match(appSource, /const nextShield = Math\.min\(5, activeSharedShield \+ 2\)/);
  assert.match(appSource, /SHIELD \+2/);
  assert.doesNotMatch(appSource, /<span>1 AP \/ SHIELD 2<\/span>/);
  assert.doesNotMatch(appSource, /SHIELD 4/);
});
